ALTER TABLE admins ADD COLUMN address VARCHAR(255) DEFAULT NULL;
ALTER TABLE admins ADD COLUMN fiscal_address VARCHAR(255) DEFAULT NULL;
ALTER TABLE admins ADD COLUMN vat_rate_default DECIMAL(5,2) DEFAULT 19.00;
